[package]
name = "classe3E"
version = "0.1.0"
authors = ["emiliano"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
